export const languageCodes = {
    "english": ["en", "EN", "En"],
    "chinese": ["zh", "ZH", "Zh"],
    "spanish": ["es", "ES", "Es"],
    "hindi": ["hi", "HI", "Hi"],
    "arabic": ["ar", "AR", "Ar"],
    "portuguese": ["pt", "PT", "Pt"],
    "bengali": ["bn", "BN", "Bn"],
    "russian": ["ru", "RU", "Ru"],
    "japanese": ["ja", "JA", "Ja"],
    "punjabi": ["pa", "PA", "Pa"],
    "german": ["de", "DE", "De"],
    "javanese": ["jw", "JW", "Jw"],
    "korean": ["ko", "KO", "Ko"],
    "french": ["fr", "FR", "Fr"],
    "telugu": ["te", "TE", "Te"],
    "marathi": ["mr", "MR", "Mr"],
    "turkish": ["tr", "TR", "Tr"],
    "tamil": ["ta", "TA", "Ta"],
    "vietnamese": ["vi", "VI", "Vi"],
    "urdu": ["ur", "UR", "Ur"],
    "persian": ["fa", "FA", "Fa"],
    "polish": ["pl", "PL", "Pl"],
    "ukrainian": ["uk", "UK", "Uk"],
    "italian": ["it", "IT", "It"],
    "thai": ["th", "TH", "Th"],
    "gujarati": ["gu", "GU", "Gu"],
    "romanian": ["ro", "RO", "Ro"],
    "dutch": ["nl", "NL", "Nl"],
    "hebrew": ["he", "HE", "He"],
    "greek": ["el", "EL", "El"],
    "swedish": ["sv", "SV", "Sv"]
  
  }
  