const allRoles = {
  customer: ['self'],

  admin: [
    'generateAdminReport',
    'manageCompany',
    'manageApartmentComplex',
    'manageApartments',
    'getUsers',
    'getNewUsers',
    'updateUser',
    'accept-reject-promote-demote',
    'manageUsers',
    'self',
    'impersonation',
    'getLogs',
    'createUser',
    'updateProfile',
    'superadmin',
    'changeEmail',
    'manageStatus',
    'manageSelfLicense',
    'manageLicenses',
    'createUserWithType',
    'getTowCompanyEmployees',
    'manageOccupant',
    'followUpTowRequest',
    'oneTimeInviteLink',
    'systemSettings',
    'jurisdiction',
    'manageVsfs',
    'getVsfs',
    'manageTiers',
    'manageSubscriptions',
    'getSubscriptions',
    'changeSubscription',
    'getSubscriptions',
    'createTow',
    'manageRoles',
  ],
  superadmin: [
    'getUsers',
    'manageUsers',
    'manageSelfLicense',
    'manageApartments',
    'self',
    'impersonation',
    'getLogs',
    'createUser',
    'updateProfile',
    'accept-reject-promote-demote',

    'changeEmail',
    'createUserWithType',
    'manageLicenses',
    'systemSettings',
    'followUpTowRequest',
    'manageVsfs',
    'getVsfs',
    'manageTiers',
    'manageSubscriptions',
    'getSubscriptions',
    'changeSubscription',
    'getSubscriptions',
    'createTow'
  ],
  'apartment-complex-owner': [
    'getUsers',
    'manageApartmentComplex',
    'updateUser',
    'manageUsers',
    'accept-reject-promote-demote',
    'self',
    'manageApartments',
    'getLogs',
    'manageSelfLicense',
    'updateProfile',
    'manageLicenses',
    'createUserWithType',
    'changeEmail',
    'manageOccupant',
    'getVsfs',
    'manageStatus',
    'getSubscriptions',
    'createTow'

  ],
  'apartment-complex-manager': [
    'getUsers',
    'manageApartmentComplex',
    'updateUser',
    'manageUsers',
    'self',
    'getLogs',
    'manageOccupant',

    'manageApartments',
    // 'getLogs',
    // 'updateProfile',
    'manageSelfLicense',
    'manageLicenses',
    'createUserWithType',
    // 'changeEmail',
    'manageStatus',
    'getVsfs',
    'getSubscriptions',
    'createTow'

  ],

  'tow-company-owner': [
    'getUsers',
    'manageUsers',
    'self',
    'updateUser',
    'getLogs',
    'updateProfile',
    'accept-reject-promote-demote',
    'getNewUsers',
    'getVsfs',
    'changeEmail',
    'createUserWithType',
    'manageStatus',
    'getTowRequests',
    'assignTow',
    'getMyTowEmployees',
    'getTowCompanyEmployees',
    'createParkingSpacesUnpaid',
      'createTow',
    'oneTimeInviteLink',
    'updateTowRequestStatus',
    'getSubscriptions',
    'changeSubscription',
    'getSubscriptions',
    
    'updateTow'

  ],
  'tow-company-manager': [
    'getUsers',
    'manageUsers',
    'self',
    'updateUser',
    'getLogs',
    'getNewUsers',
    'getMyTowEmployees',
    'getVsfs',
    
    // 'getLogs',
    // 'updateProfile',

    // 'changeEmail',
    'createUserWithType',
    'manageStatus',
    'changeSubscription',

    'getTowCompanyEmployees',
    'getTowRequests',
    'assignTow',
    'createParkingSpacesUnpaid',
      'createTow',
    'oneTimeInviteLink',
    'updateTowRequestStatus',
    'getSubscriptions',

    'updateTow'
    
  ],
  'tow-company-employee': [
    'getUsers',
    'self',
    'getLogs',
    'updateProfile',
    'getTowRequests',
    'updateTowRequestStatus',
    'assignTow',
    'createTow',
    'updateTow',
    'getVsfs',
    'getSubscriptions',

  ],
  'apartment-complex-employee': [
    'getUsers',
    'updateUser', // to be managed
    'createUserWithType',
    'manageApartments',
    'self',
    'getLogs',
    'updateProfile',
    'manageOccupant',
    'manageLicenses',
    'getVsfs',
    'manageSelfLicense',
    'getSubscriptions'

  ],
  renter: ['self', 'getUsers', 'manageSelfLicense', 'manageOccupant', 'changeEmail',],
  'parking-spaces-provider-owner': [
    'self',
    'getUsers',
    'manageSelfLicense',
    'manageOccupant',
    'changeEmail',
    'createTow',
    'followUpTowRequest',
    'updateTowRequestStatus',
    'getTowRequests',
    'getVsfs',
    'getSubscriptions'

  ],
  'parking-spaces-provider-manager': [
    'self',
    'getUsers',
    'manageSelfLicense',
    'manageOccupant',
    'changeEmail',
    'createTow',
    'followUpTowRequest',
    'getVsfs',
    'getTowRequests',
    'getSubscriptions'

  ],
  'parking-spaces-provider-employee': [
    'self',
    'getUsers',
    'manageSelfLicense',
    'manageOccupant',
    'changeEmail',
    'createTow',
    'followUpTowRequest',
    'getVsfs',
    'getTowRequests',
    'getSubscriptions'

  ],
  'tow-requester': [
    'self',
    'getUsers',
    'manageSelfLicense',
    'manageOccupant',
    'changeEmail',
    'createTow',
    'followUpTowRequest',
    'getVsfs',
    'getTowRequests',
    'getSubscriptions'

  ],
};

export const roles: string[] = Object.keys(allRoles);
export const roleRights: Map<string, string[]> = new Map(Object.entries(allRoles));
